server:
  port: 10000

aws:
  dynamodb:
    region: ${AWS_REGION}
    endpoint: https://dynamodb.${AWS_REGION}.amazonaws.com

spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/static/
  application:
    name: fondo-service

  main:
    allow-bean-definition-overriding: true

  devtools:
    restart:
      enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs


logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN
    org.springframework.web: INFO