server:
  port: 10000

aws:
  dynamodb:
    region: ${AWS_REGION}
    endpoint: https://dynamodb.${AWS_REGION}.amazonaws.com

spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/static/
  application:
    name: fondo-service

  main:
    allow-bean-definition-overriding: true

  devtools:
    restart:
      enabled: false

springdoc:
  api-docs:
    path: /dev/v3/api-docs
  swagger-ui:
    path: /dev/swagger-ui.html
    config-url: /dev/v3/api-docs/swagger-config
    use-root-path: true

logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN
    org.springframework.web: INFO